### ISSUE TITLE
How to fail a build if size of file is greater than maxSize

### ISSUE THREAD

**Issue by kandarp1691** [jaysalvat/gulp-sizereport#18]
I am trying to fail a build using the documentation provided and have come up with 
```
gulp.task('sizereport', function () {
    return gulp.src('./dist/scripts/*.js')
        .pipe(sizereport({
          '*' : {
            'maxSize': 100000,
            'fail' : true
          }
        }));
});
```
It does give me the output in red color but doesnt fail the build. What am I missing?

**Comment by jaysalvat** [comment]
Hello. 
It doesn't fail.
It is a tool made for myself and I didn't need to fail. Just to be reported.

**Comment by kandarp1691** [comment]
Cool. Thanks for updating.
