### ISSUE TITLE
Detect files that are already minified

### ISSUE THREAD

**Issue by webdesserts** [jaysalvat/gulp-sizereport#2]
Hi! I like the report. I've been using gulp-size, but when you're working with a library it can get very verbose and annoying. This module's output is very nice and clean.

One thing that would make it better is if you it could automatically detect already minified files (with the pattern `*.min.js`) and add them to the table, without minifying them after the fact. When I'm building a library, most of the time these files are already minified (possibly with custom settings) and it's kind of a waste to minify them again, just for the size-report.

For example on the project I'm currently using size-report for, I get this report when I pipe in my `./dist` directory:

![report](https://www.dropbox.com/s/cn4wxu2t8efud4u/Screenshot%202015-05-09%2016.26.07.png?dl=1)

**Comment by jaysalvat** [comment]
Hello and thanks for your feedbacks.

The filepath is now passed to the minifier function. Use it to detect whatever you want.

``` javascript
    gulp.task('sizereport', function () {
        return gulp.src('./src/**/*.js')
            .pipe(sizereport({
                minifier: function (contents, filepath) {
                    if (filepath.match(/\.min\./g)) {
                        return contents
                    }
                    return UglifyJS.minify(contents, { fromString: true }).code;
                }
            }));
    });
```

:)
