### ISSUE TITLE
Sizereport is not working for my JS file.

### ISSUE THREAD

**Issue by chrisdemars** [jaysalvat/gulp-sizereport#5]
I am having trouble getting this to work. . I keep getting a "ReferenceError: sizereport is not defined at...". Is there a break down of how to actually use this against files? Thanks.

**Comment by jaysalvat** [comment]
Hello,

It seems you didn't install install or require sizereport.

Installation:

```
npm install --save-dev gulp-sizereport
```

Usage with Gulp

```
var gulp = require('gulp');
var sizereport = require('gulp-sizereport');

gulp.task('sizereport', function () {
    return gulp.src('./dist/*')
        .pipe(sizereport());
});
```

**Comment by chrisdemars** [comment]
I have it figured out now. It wasn't the plugin, it was other stuff I was
having issues with.

**Comment by jaysalvat** [comment]
Ok :)
