### ISSUE TITLE
Use with gulp-cssnano and gulp-uglify

### ISSUE THREAD

**Issue by movie4** [jaysalvat/gulp-sizereport#6]
Hello!

Is it possible to use this plugin together with the [gulp-cssnano](https://www.npmjs.com/package/gulp-cssnano) and [gulp-uglify](https://www.npmjs.com/package/gulp-uglify) without install standalone [cssnano](https://github.com/ben-eb/cssnano) and [uglifyjs](https://github.com/mishoo/UglifyJS2)

Thanks for great plugin

**Comment by jaysalvat** [comment]
Hello,
No, sorry :)
