### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by bshack** [jaysalvat/gulp-sizereport#7]
Can a table title be defined in the options for the data table and then be output above the table in the console output? For Example the data table with a title of 'CSS Files' defined in the options:

CSS Files

┌────────────────────┬───────────┬───────────┐
│ File               │  Original │   Gzipped │
├────────────────────┼───────────┼───────────┤
│ global.compiled.js │ 445.25 kB │ 125.08 kB │
├────────────────────┼───────────┼───────────┤
│ index.compiled.js  │  572.2 kB │ 135.66 kB │
├────────────────────┼───────────┼───────────┤
│ style.compiled.js  │   4.34 kB │   1.83 kB │
├────────────────────┼───────────┼───────────┤
│                    │   1.02 MB │ 262.57 kB │
└────────────────────┴───────────┴───────────┘

Thanks!

**Comment by jaysalvat** [comment]
Hello,

Please try.
https://github.com/jaysalvat/gulp-sizereport#options
