### ISSUE TITLE
Print nothing when there are more than 16 files

### ISSUE THREAD

**Issue by iamyy** [jaysalvat/gulp-sizereport#8]
Great job! But I was wondering that it prints nothing when I have more than 16 files in my project. And I have tried "gulp-size" plugin which has the save problem... Really odd.

**Comment by jaysalvat** [comment]
Hello,

It's seems this is a Through2 limitation. Many plugins are impacted.
https://github.com/rvagg/through2/issues/82

However, I can't reproduce this issue.
I made a test with 20 files and everything seems ok to me.

**Comment by iamyy** [comment]
Yeah, that is a Through2 limitation, and I' m thinking about how to deal with it. Thank you for reply~😆
